### ISSUE TITLE
ModuleNotFoundError: No module named 'wtforms.fields.html5'

### ISSUE THREAD

**Issue by alex-dem** [FAIRplus/imi-data-catalogue#15]
I am trying to install a local installation on a Ubuntu 18.04 VM. 
Regarding the dependencies I have found that I need to install the packages
`
libldap2-dev npm libsasl2-dev python3.7 python3-pip python3.7-venv libpython3.7-dev openjdk-8-jre-headless`

And of course solr (version 8.8.2)

At first 
`
python setup.py install`

does not run successfully, so I had to install the following python packages
```

python3 -m pip install setuptools-rust
python3 -m pip install wheel
python3 -m pip install  requests
python3 -m pip install  flask==0.10.1
python3 -m pip install  werkzeug==0.16.1
```

And I upgrade npm to version 7.5.6 in three steps, since for some reason it couldn’t upgrade directly from 3.8 to 7.6.5
```

sudo npm install -g npm@4.0.0
sudo npm install -g npm@5.0.0
sudo npm install -g npm@7.5.6
```

After that, I follow all the installation steps successfully and execute the final command to run the development server:
`./manage.py runserver`

However, when I connect to localhost:5000 I see on my browser the error message:
"
cannot open page:
ModuleNotFoundError

ModuleNotFoundError: No module named 'wtforms.fields.html5'
"
and corresponding errors on the debug console from the server side.

Any help from your side would be highly appreciated.

**Comment by neoflex** [comment]
Hi @alex-dem,

thanks for the interest and for creating this issue.
Here is the list of python dependencies with their exact version that we are using:


requirements = [
    'Flask==1.1.2', 'Flask-Assets==2.0', 'Flask-Script==2.0.6', 'Jinja2==2.11.3', 'SQLAlchemy==1.4.5',
    'werkzeug==0.16.1', 'closure==20191111',
    'cssmin==0.2.0', 'webassets==2.0', 'Flask-Testing==0.8.1', 'requests==2.25.1', 'GEOparse==2.0.3',
    'Flask-Caching==1.10.1', 'python-ldap==3.3.1',
    'Flask-Login==0.5.0', 'Flask-WTF==0.14.3', 'pysolr==3.8.1', 'ckanapi==4.3', 'Flask-Mail==0.9.1',
    'flask-reverse-proxy-fix==0.2.1', 'email-validator==1.1.1', 'oic==1.2.0', 'jsonpath-ng==1.5.2'
]

we need to modify setup.py to match this but meanwhile, it should work to manually install those.

**Comment by neoflex** [comment]
I've pushed a new version on develop where all dependencies versions are fixed to avoid such issues.
I hope this solves it for you. let us know!

**Comment by alex-dem** [comment]
Hello again. Unfortunately, after downloading the develop branch, I still get the same response "ModuleNotFoundError: No module named 'wtforms.fields.html5'". 
Exactly like before; I am also attaching a screenshot

![image](https://user-images.githubusercontent.com/8984850/121701971-1f323f00-cada-11eb-9aea-20430adef71e.png)

**Comment by neoflex** [comment]
issue seems to happen on ubuntu, will investigate

**Comment by yjarosz** [comment]
Hello @neoflex, I think I found the issue, from WTForms 3.xxx, the widgets are HTML5 by default (see [changelog](https://wtforms.readthedocs.io/en/3.0.x/changes/#version-3-0-0a1)). Downgrading to 2.3.3 works.

**Comment by neoflex** [comment]
thanks @yjarosz,  the fix is indeed to specify the wtforms version in setup.py.
the root cause is that flask-wtforms is not using a fixed version for its wtforms dependency: https://github.com/wtforms/flask-wtf/blob/v0.14.3/setup.py 
so, fixing the flask-wtforms version as we were doing is not enough. Will push a fix.

for @alex-dem, that's the issue we already debugged together some weeks ago, so no changes needed for your deployment for now.
